<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
    <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
    <div class="form-group">

	<p> Configure the following values according to the <a href="https://github.com/printfuck/xExtension-Readable#setup" target="_blank">instructions</a> </p>
	<label class="group-name" for="read_readability_host">Readbility Host</label>
	<div class="group-controls">
	    <input type="text" id="read_readability_host" name="read_readability_host" value="<?php echo $this->getReadHost(); ?>" min="50" data-leave-validation="1">
	</div>

	<label class="group-name" for="read_mercury_host">Mercury Host</label>
	<div class="group-controls">
	    <input type="text" id="read_mercury_host" name="read_mercury_host" value="<?php echo $this->getMercHost(); ?>" min="100" data-leave-validation="1">
	</div>
    </div>

    <div>
	<p>Shown below are the feeds, to which this addon will apply either Mercury or Readability Parsing. Remember to hit <b>Submit</b> at the bottom after making changes.</p>
	<?php
		foreach ($this->getCategories() as $c) {
	?>

		<h3><?php echo $c->name()?></h3>
		<table>
		<tr><td>Mercury</td><td>Readability</td><td>Feed</td></tr>
		<?php
			foreach ( $c->feeds() as $f) {
		?>

			<tr>
			<td> <input type="checkbox" id="merc_<?php echo $f->id() ?>" name="merc_<?php echo $f->id() ?>" value="1" <?php echo $this->getConfStoreM($f->id()) ? 'checked' : ''; ?>> </td>
			<td> <input type="checkbox" id="read_<?php echo $f->id() ?>" name="read_<?php echo $f->id() ?>" value="1" <?php echo $this->getConfStoreR($f->id()) ? 'checked' : ''; ?>> </td>
	    		<td><?php echo $f->name() ?></td>
			</tr>
		
		<?php
			}
		?>
		</table>
	<?php
		}
	?>
	<br>
    </div>

    <div class="form-group form-actions">
	<div class="group-controls">
	    <button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
	    <button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
	</div>
    </div>
</form>
