<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="image-height"><?php echo _t('ext.reddit_image.image_height'); ?></label>
		<div class="group-controls">
            <input type="number" name="image-height" id="image-height" value="<?php echo $this->image_height; ?>" min="1" max="100"/>
            <?php echo _t('ext.reddit_image.image_height_unit'); ?>
		</div>
	</div>

	<div class="form-group">
		<div class="group-controls">
			<label class="checkbox" for="muted-video">
				<input type="checkbox" name="muted-video" id="muted-video" value="1" <?= $this->muted_video ? 'checked=true' : '' ?>/>
				<?= _t('ext.reddit_image.muted_video'); ?>
			</label>
		</div>
	</div>

	<div class="form-group">
		<div class="group-controls">
			<label class="checkbox" for="display-image">
				<input type="checkbox" name="display-image" id="display-image" value="1" <?= $this->display_image ? 'checked=true' : '' ?>/>
				<?= _t('ext.reddit_image.display_image'); ?>
			</label>
		</div>
	</div>

	<div class="form-group">
		<div class="group-controls">
			<label class="checkbox" for="display-video">
				<input type="checkbox" name="display-video" id="display-video" value="1" <?= $this->display_video ? 'checked=true' : '' ?>/>
				<?= _t('ext.reddit_image.display_video'); ?>
			</label>
		</div>
	</div>

	<div class="form-group form-actions">
		<?php if (isset($this->permission_problem)) { ?>
			<p class="alert alert-error"><?php echo _t('ext.reddit_image.permission_problem', $this->permission_problem); ?></p>
		<?php } else { ?>
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
				<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
			</div>
		<?php } ?>
	</div>
</form>