<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
    <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
    <div class="form-group">

	<label class="group-name" for="read_readability_host">Readbility Host</label>
	<div class="group-controls">
	    <input type="text" id="read_readability_host" name="read_readability_host" value="<?php echo $this->getReadHost(); ?>" min="50" data-leave-validation="1">
	</div>

	<label class="group-name" for="read_mercury_host">Mercury Host</label>
	<div class="group-controls">
	    <input type="text" id="read_mercury_host" name="read_mercury_host" value="<?php echo $this->getMercHost(); ?>" min="100" data-leave-validation="1">
	</div>
    </div>

    <div>
	<p> Shown below are the feeds, on which this addon will apply either Mercury or Readability Parsing </p>
	<table>
	<tr> <td>Mercury</td><td>Readability</td><td>Feed</td></tr>
	<?php
		foreach ($this->getFeeds() as $f) {
	?>
		<tr>
			<td> <input type="checkbox" id="merc_<?php echo $f->id() ?>" name="merc_<?php echo $f->id() ?>" value="1" <?php echo $this->getConfStore('m', $f->id()) ? 'checked' : ''; ?>> </td>
			<td> <input type="checkbox" id="read_<?php echo $f->id() ?>" name="read_<?php echo $f->id() ?>" value="1" <?php echo $this->getConfStore('r', $f->id()) ? 'checked' : ''; ?>> </td>
	    		<td><?php echo $f->name() ?></td>
		</tr>
		
	<?php
		}
	?>
	</table>
    </div>

    <div class="form-group form-actions">
	<div class="group-controls">
	    <button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
	    <button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
	</div>
    </div>
</form>
